import subprocess
from pathlib import Path
from typing import Optional


class VideoProcessor:
    def __init__(self, target_fps: int = 30):
        self.target_fps = target_fps

    def process_video(
        self,
        input_path: Path,
        output_path: Path,
        trim_start: float = 0.5,
        trim_end: float = 0.5,
    ) -> Path:
        if not input_path.exists():
            raise FileNotFoundError(f"Input video not found: {input_path}")

        output_path.parent.mkdir(parents=True, exist_ok=True)

        duration = self._get_video_duration(input_path)

        if duration <= (trim_start + trim_end):
            trim_start = 0
            trim_end = 0

        cmd = [
            "ffmpeg",
            "-i",
            str(input_path),
            "-ss",
            str(trim_start),
            "-to",
            str(duration - trim_end) if trim_end > 0 else str(duration),
            "-c:v",
            "libx264",
            "-preset",
            "medium",
            "-crf",
            "23",
            "-r",
            str(self.target_fps),
            "-pix_fmt",
            "yuv420p",
            "-movflags",
            "+faststart",
            "-y",
            str(output_path),
        ]

        try:
            subprocess.run(
                cmd,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                timeout=120,
            )
        except subprocess.CalledProcessError as e:
            raise RuntimeError(f"FFmpeg processing failed: {e.stderr.decode()}")
        except subprocess.TimeoutExpired:
            raise RuntimeError("FFmpeg processing timed out")

        if not output_path.exists():
            raise RuntimeError("Output video was not created")

        return output_path

    def _get_video_duration(self, video_path: Path) -> float:
        cmd = [
            "ffprobe",
            "-v",
            "error",
            "-show_entries",
            "format=duration",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
            str(video_path),
        ]

        try:
            result = subprocess.run(
                cmd,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                timeout=10,
            )
            duration_str = result.stdout.decode().strip()
            return float(duration_str)
        except:
            return 0.0

    def discover_video_file(self, directory: Path) -> Path:
        if not directory.exists() or not directory.is_dir():
            raise FileNotFoundError(f"Video directory not found: {directory}")
            
        # Discover webm files generated by Playwright
        videos = list(directory.glob("*.webm"))
        
        if not videos:
            raise FileNotFoundError(f"No video files found in {directory}")
            
        # Return the largest file (most likely the full recording)
        return max(videos, key=lambda p: p.stat().st_size)

    def cleanup(self, *paths: Path):
        for path in paths:
            if path and path.exists():
                try:
                    path.unlink()
                except:
                    pass
